"""Add semester and faculty_id to subjects

Revision ID: 078ebf8cd874
Revises: eabf0611acd8
Create Date: 2026-07-04 00:26:49.673071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078ebf8cd874'
down_revision: Union[str, Sequence[str], None] = 'eabf0611acd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('faculty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'faculty', ['faculty_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'faculty_id')
    op.drop_column('subjects', 'semester')
    # ### end Alembic commands ###
