"""Update SubstituteFacultyAssignment for specific lecture instances

Revision ID: 7afa03d17e78
Revises: 13a3203ecec3
Create Date: 2026-08-02 22:38:26.563917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7afa03d17e78'
down_revision: Union[str, Sequence[str], None] = '13a3203ecec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substitute_faculty_assignments', sa.Column('lecture_instance_id', sa.String(length=100), nullable=True))
    op.alter_column('substitute_faculty_assignments', 'subject_assignment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('substitute_faculty_assignments', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('substitute_faculty_assignments', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('substitute_faculty_assignments', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('substitute_faculty_assignments', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('substitute_faculty_assignments', 'subject_assignment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('substitute_faculty_assignments', 'lecture_instance_id')
    # ### end Alembic commands ###
