"""add_lecture_fields_to_attendance

Revision ID: 9ec335d2b1e3
Revises: dd59f698d890
Create Date: 2026-08-05 21:26:43.879908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec335d2b1e3'
down_revision: Union[str, Sequence[str], None] = 'dd59f698d890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('lecture_id', sa.String(length=150), nullable=True))
    op.add_column('attendance', sa.Column('time', sa.String(length=10), nullable=True))
    op.add_column('attendance', sa.Column('attendance_method', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_attendance_lecture_id'), 'attendance', ['lecture_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_lecture_id'), table_name='attendance')
    op.drop_column('attendance', 'attendance_method')
    op.drop_column('attendance', 'time')
    op.drop_column('attendance', 'lecture_id')
    # ### end Alembic commands ###
