"""Add status to SubstituteFacultyAssignment

Revision ID: dd59f698d890
Revises: 7afa03d17e78
Create Date: 2026-08-02 23:17:05.014878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd59f698d890'
down_revision: Union[str, Sequence[str], None] = '7afa03d17e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substitute_faculty_assignments', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('substitute_faculty_assignments', 'status')
    # ### end Alembic commands ###
